/** Settings → Data sources, in English and Chinese. */
export const COPY = {
  en: {
    title: "Data sources",
    intro: "The databases checks run against. Every query runs in a read-only transaction; give each source a role that can only SELECT.",
    count: (n: number) => (n === 1 ? "1 data source" : `${n} data sources`),
    add: "Add data source",
    none: "No data sources yet. Set DATABASE_URL, or add one here.",
    loadFailed: "Could not load data sources",
    readOnly: "Only admins can add or change data sources.",
    noKey: "Set ASSAY_SECRET_KEY on the server to add data sources: it encrypts their connection strings.",
    builtIn: "Built-in",
    fromEnv: "From DATABASE_URL, set in the environment",
    hidden: "Connection hidden in the demo",
    checks: (n: number) => (n === 1 ? "1 check" : `${n} checks`),
    neverTested: "Not tested yet",
    connected: (when: string) => `Connected ${when}`,
    canWrite: "role can write",
    failed: (when: string) => `Failed ${when}`,
    test: "Test",
    testing: "Testing…",
    edit: "Edit",
    remove: "Delete",
    more: "More",
    // Dialog
    addTitle: "Add a data source",
    editTitle: "Edit data source",
    addDescription: "A PostgreSQL database checks can run against.",
    name: "Name",
    namePlaceholder: "e.g. Billing replica",
    id: "ID",
    idHint: "Checks refer to it by this ID. Lowercase letters, numbers and hyphens.",
    idFixed: "Cannot be changed after creation",
    connection: "Connection string",
    connectionHint: "Stored encrypted and never shown again.",
    connectionKeep: (display: string) => `Leave empty to keep the current connection (${display}).`,
    connectionKeepHidden: "Leave empty to keep the current connection.",
    testConnection: "Test connection",
    testFirst: "Type a connection string to test it.",
    cancel: "Cancel",
    close: "Got it",
    save: "Save",
    saving: "Saving…",
    added: "Data source added",
    saved: "Data source saved",
    // Test result
    resultOk: (version: string, user: string) => `Connected to PostgreSQL ${version} as ${user}.`,
    resultWrite: (how: string) =>
      `This role can write (${how}). Checks only need SELECT: create a read-only role for Assay.`,
    resultFailed: "Could not connect",
    access: {
      superuser: "superuser",
      pg_write_all_data: "pg_write_all_data",
      table_write: "write privileges on tables",
      create_schema: "CREATE on the database",
    } as Record<string, string>,
    // Delete
    removeTitle: (name: string) => `Delete ${name}?`,
    removeBody: "Checks can no longer use it. Its connection string is deleted and cannot be recovered.",
    removeBlocked: (n: number) =>
      `${n === 1 ? "1 check uses" : `${n} checks use`} this data source. Move ${n === 1 ? "it" : "them"} to another source before deleting it.`,
    removed: "Data source deleted",
  },
  zh: {
    title: "数据源",
    intro: "检查所读取的数据库。所有查询都在只读事务中执行；请为每个数据源使用只有 SELECT 权限的账号。",
    count: (n: number) => `${n} 个数据源`,
    add: "添加数据源",
    none: "还没有数据源。请设置 DATABASE_URL，或在这里添加。",
    loadFailed: "无法加载数据源",
    readOnly: "只有管理员可以添加或修改数据源。",
    noKey: "请在服务器上设置 ASSAY_SECRET_KEY 后再添加数据源，它用来加密连接串。",
    builtIn: "内置",
    fromEnv: "来自环境变量 DATABASE_URL",
    hidden: "演示模式下不显示连接信息",
    checks: (n: number) => `${n} 个检查`,
    neverTested: "尚未测试",
    connected: (when: string) => `${when}连接成功`,
    canWrite: "账号可写",
    failed: (when: string) => `${when}连接失败`,
    test: "测试",
    testing: "测试中…",
    edit: "编辑",
    remove: "删除",
    more: "更多",
    addTitle: "添加数据源",
    editTitle: "编辑数据源",
    addDescription: "检查可以读取的 PostgreSQL 数据库。",
    name: "名称",
    namePlaceholder: "例如：账单只读副本",
    id: "ID",
    idHint: "检查通过这个 ID 引用数据源。只能用小写字母、数字和连字符。",
    idFixed: "创建后不可修改",
    connection: "连接串",
    connectionHint: "加密保存，保存后不再显示。",
    connectionKeep: (display: string) => `留空则保留当前连接（${display}）。`,
    connectionKeepHidden: "留空则保留当前连接。",
    testConnection: "测试连接",
    testFirst: "请先填写连接串再测试。",
    cancel: "取消",
    close: "知道了",
    save: "保存",
    saving: "保存中…",
    added: "数据源已添加",
    saved: "数据源已保存",
    resultOk: (version: string, user: string) => `已连接 PostgreSQL ${version}，账号 ${user}。`,
    resultWrite: (how: string) => `这个账号有写权限（${how}）。检查只需要 SELECT，建议为 Assay 创建只读账号。`,
    resultFailed: "连接失败",
    access: {
      superuser: "超级用户",
      pg_write_all_data: "pg_write_all_data",
      table_write: "表的写权限",
      create_schema: "数据库的 CREATE 权限",
    } as Record<string, string>,
    removeTitle: (name: string) => `删除 ${name}？`,
    removeBody: "删除后检查将无法再使用它，连接串也会一并删除且无法恢复。",
    removeBlocked: (n: number) => `有 ${n} 个检查正在使用这个数据源，请先把它们改到其他数据源再删除。`,
    removed: "数据源已删除",
  },
};

export type Copy = (typeof COPY)["en"];
