const en = {
  pageTitle: "All checks edit history",
  pageDescription: "View and filter the edit history of all checks.",
  noResults: "No results",
  noData: "No data",
  scheduled: "Scheduled",
  manual: "Manual",
  operations: { create: "Create", update: "Update", delete: "Delete" } as Record<string, string>,
  allOperations: "All",
  noChanges: "No changes",
  changeCount: (count: number) => `${count} changes`,
  // Toolbar
  scriptName: "Check name",
  searchPlaceholder: "Search check name, description or ID...",
  operationType: "Operation type",
  selectOperation: "Select an operation type",
  author: "Author",
  dateFrom: "Date from",
  dateTo: "Date to",
  resetFilters: "Reset filters",
  search: "Search edit history",
  // Table
  errorTitle: "Data loading failed",
  retry: "Retry load",
  noHistory: "No edit history found",
  noHistoryHint: "Try adjusting your filters or change a check to see history.",
  operationUser: "Operation user",
  operationTime: "Operation time",
  fieldChanges: "Field changes",
  actions: "Actions",
  unknownScript: "Unknown check",
  unknownUser: "Unknown user",
  viewDetails: "Check details",
  // Detail dialog
  detailTitle: "Edit history details",
  description: "Description",
  checkSection: "Check details",
  scriptNameCn: "Check Name (CN)",
  scriptId: "Check ID",
  unknown: "Unknown",
  changesDetails: "Changes details",
  originalValue: "Original value",
  newValue: "New value",
  // One check's history dialog
  dialogTitle: "Edit history",
  dialogDescription: "Showing edit history for the selected check",
  loading: "Loading edit history...",
  previous: "Previous",
  next: "Next",
  pageInfoShort: "Showing %s-%s of %s results (Page %s of %s)",
};

export type EditHistoryCopy = typeof en;

const zh: EditHistoryCopy = {
  pageTitle: "所有检查历史",
  pageDescription: "查看和筛选所有检查的编辑历史。",
  noResults: "无结果",
  noData: "无数据",
  scheduled: "计划中",
  manual: "手动",
  operations: { create: "创建", update: "更新", delete: "删除" },
  allOperations: "全部",
  noChanges: "没有更改",
  changeCount: (count) => `${count} 项变更`,
  scriptName: "检查名称",
  searchPlaceholder: "搜索检查名称、描述或ID...",
  operationType: "操作类型",
  selectOperation: "请选择操作类型",
  author: "作者",
  dateFrom: "起始日期",
  dateTo: "结束日期",
  resetFilters: "重置过滤器",
  search: "搜索编辑历史",
  errorTitle: "数据加载失败",
  retry: "重试加载",
  noHistory: "没有编辑历史",
  noHistoryHint: "尝试调整筛选条件或修改一个检查后再查看历史记录。",
  operationUser: "操作用户",
  operationTime: "操作时间",
  fieldChanges: "字段更改",
  actions: "操作",
  unknownScript: "未知检查",
  unknownUser: "未知用户",
  viewDetails: "检查详情",
  detailTitle: "编辑历史详情",
  description: "描述",
  checkSection: "检查详情",
  scriptNameCn: "检查名称 (中文)",
  scriptId: "检查 ID",
  unknown: "未知",
  changesDetails: "更改详情",
  originalValue: "原始值",
  newValue: "新值",
  dialogTitle: "编辑历史",
  dialogDescription: "显示所选检查的编辑历史",
  loading: "加载编辑历史...",
  previous: "上一页",
  next: "下一页",
  pageInfoShort: "显示第 %s-%s 条，共 %s 条结果（第 %s 页/共 %s 页）",
};

export function editHistoryCopy(language: string): EditHistoryCopy {
  return language === "zh" ? zh : en;
}
