export type Tab = "result" | "history" | "definition" | "triage";

export const COPY = {
  en: {
    since: (when: string) => `since ${when}`,
    neverRan: "Not run yet",
    runNow: "Run now",
    running: "Running…",
    edit: "Edit",
    lastRuns: (n: number) => `Last ${n} runs`,
    rowsFlagged: "Rows flagged",
    now: "now",
    previous: "previous run",
    high: "30-run high",
    tabs: { result: "Latest result", history: "Run history", definition: "Query & schedule", triage: "AI triage" },
    compared: "Compared with the previous run",
    firstRun: "First run: nothing to compare with yet",
    newRows: (n: number) => `${n} new`,
    stillRows: (n: number) => `${n} still open`,
    fixedRows: (n: number) => `${n} fixed`,
    markNew: "New",
    markStill: "Still open",
    markFixed: "Fixed",
    shownOf: (shown: number, total: number) => `Showing ${shown} of ${total} rows. The full set is in the report.`,
    fullReport: "Full report",
    noRows: "No rows returned",
    passed: "This check passed.",
    failed: "The query failed",
    notRun: "This check has not run yet. Run it to see what it finds.",
    run: "Run",
    trigger: "Trigger",
    result: "Result",
    change: "Change",
    duration: "Duration",
    triggers: { manual: "Manual", schedule: "Scheduled", batch: "Batch", api: "API" } as Record<string, string>,
    queryError: "Query error",
    rows: (n: number) => (n === 1 ? "1 row" : `${n} rows`),
    query: "Query",
    readOnly: "Read-only",
    schedule: "Schedule",
    nextRun: (when: string) => `Next run ${when}`,
    reads: "Reads",
    tags: "Tags",
    scope: "Scope",
    author: "Author",
    created: "Created",
    triageIntro: "AI reads the query, the schema and the shape of the returned rows (never their values) and suggests what to look at.",
    triageRun: "Triage the latest run",
    triaging: "Triaging…",
    triageOff: "AI is switched off in this workspace.",
    triageClean: "The latest run is clean. There is nothing to triage.",
    kind: { data_issue: "Data issue", check_error: "Problem in the check", needs_review: "Needs review" } as Record<string, string>,
    causes: "Likely causes",
    nextSteps: "Next steps",
    fixedSql: "Corrected query",
    notFound: "No check with this id.",
    back: "Back to checks",
    runFailed: "Could not run the check",
    ranClean: "Run finished: clean",
    ranIssues: (n: number) => (n === 1 ? "Run finished: 1 row needs attention" : `Run finished: ${n} rows need attention`),
    ranError: "Run finished: the query failed",
  },
  zh: {
    since: (when: string) => `${when}起`,
    neverRan: "尚未执行",
    runNow: "立即执行",
    running: "执行中…",
    edit: "编辑",
    lastRuns: (n: number) => `最近 ${n} 次执行`,
    rowsFlagged: "标出的行数",
    now: "当前",
    previous: "上一次",
    high: "30 次最高",
    tabs: { result: "最新结果", history: "执行历史", definition: "查询与定时", triage: "AI 分诊" },
    compared: "与上一次执行对比",
    firstRun: "首次执行，暂无可对比的结果",
    newRows: (n: number) => `新增 ${n}`,
    stillRows: (n: number) => `仍未解决 ${n}`,
    fixedRows: (n: number) => `已修复 ${n}`,
    markNew: "新增",
    markStill: "仍未解决",
    markFixed: "已修复",
    shownOf: (shown: number, total: number) => `显示 ${total} 行中的前 ${shown} 行，完整结果见报告。`,
    fullReport: "完整报告",
    noRows: "没有返回任何行",
    passed: "这个检查通过了。",
    failed: "查询执行失败",
    notRun: "这个检查还没有执行过，执行一次看看它能发现什么。",
    run: "执行",
    trigger: "触发方式",
    result: "结果",
    change: "变化",
    duration: "耗时",
    triggers: { manual: "手动", schedule: "定时", batch: "批量", api: "API" } as Record<string, string>,
    queryError: "查询出错",
    rows: (n: number) => `${n} 行`,
    query: "查询",
    readOnly: "只读",
    schedule: "定时",
    nextRun: (when: string) => `下次执行：${when}`,
    reads: "读取的表",
    tags: "标签",
    scope: "范围",
    author: "作者",
    created: "创建时间",
    triageIntro: "AI 会读取查询、表结构和返回行的形态（不读取具体数值），给出排查方向。",
    triageRun: "分诊最新一次执行",
    triaging: "分诊中…",
    triageOff: "这个工作区没有开启 AI。",
    triageClean: "最新一次执行是正常的，不需要分诊。",
    kind: { data_issue: "数据问题", check_error: "检查本身有误", needs_review: "需要人工判断" } as Record<string, string>,
    causes: "可能原因",
    nextSteps: "下一步",
    fixedSql: "修正后的查询",
    notFound: "找不到这个检查。",
    back: "返回检查列表",
    runFailed: "无法执行检查",
    ranClean: "执行完成：正常",
    ranIssues: (n: number) => `执行完成：${n} 行需要处理`,
    ranError: "执行完成：查询出错",
  },
};

export type Copy = (typeof COPY)["en"];
