import type { ChannelKind } from "@/domain/notify";

/** A channel added by pasting its webhook URL; Telegram links through its bot instead. */
export type PasteKind = Exclude<ChannelKind, "telegram">;

/** The copy of Settings → Notifications. */
export const COPY = {
  en: {
    title: "Notifications",
    intro: "Alerts go where your team already works when a check breaks, finds rows, or recovers. Each alert is sent once per destination, and retried if the service is down.",
    connect: "Connect a channel",
    oneClick: (name: string) => `Add to ${name}`,
    paste: "Paste webhook URL",
    orPaste: "or paste a URL",
    telegramConnect: "Connect",
    notSetUp: "Not set up on this server",
    destinations: "Destinations",
    none: "No destinations yet. Connect a channel above and alerts start with the next change.",
    everyCheck: "All checks",
    tagged: (tags: string) => `Tagged ${tags}`,
    neverSent: "Nothing sent yet",
    sent: (when: string) => `Delivered ${when}`,
    failed: (when: string) => `Failed ${when}`,
    sendTest: "Send test",
    edit: "Edit",
    remove: "Remove",
    removeTitle: "Remove destination?",
    removeConfirm: (name: string) => `Alerts will stop going to ${name}. You can connect it again later.`,
    cancel: "Cancel",
    testSent: "Test alert sent",
    testFailed: (error: string) => `Test failed: ${error}`,
    removed: "Destination removed",
    paused: "Paused",
    digestAt: (time: string) => `Daily summary ${time}`,
    remindEvery: (h: number) => `Reminds after ${h < 24 ? `${h} h` : "1 day"}`,
    connected: "Channel connected. Send a test to see how alerts look.",
    oauthError: {
      cancelled: "Connection cancelled.",
      state: "The connection expired or was started elsewhere. Try again.",
      exchange: "The service did not return a channel. Try again.",
      unknown: "Unknown integration.",
    } as Record<string, string>,
    readOnly: "Only admins and managers can change where alerts go.",
    noKey: "Alerts are off: set ASSAY_SECRET_KEY on the server to store channel secrets.",
    loadFailed: "Could not load notification settings",
    count: (n: number) => (n === 1 ? "1 destination" : `${n} destinations`),
  },
  zh: {
    title: "通知",
    intro: "检查出错、发现问题或恢复正常时，告警会发到团队常用的地方。每条告警对每个渠道只发一次，服务暂时不可用时会自动重试。",
    connect: "连接渠道",
    oneClick: (name: string) => `添加到 ${name}`,
    paste: "粘贴 Webhook 地址",
    orPaste: "或粘贴地址",
    telegramConnect: "连接",
    notSetUp: "服务器未配置",
    destinations: "通知渠道",
    none: "还没有通知渠道。在上方连接一个渠道，下次状态变化时就会收到告警。",
    everyCheck: "所有检查",
    tagged: (tags: string) => `标签：${tags}`,
    neverSent: "尚未发送",
    sent: (when: string) => `${when}送达`,
    failed: (when: string) => `${when}发送失败`,
    sendTest: "发送测试",
    edit: "编辑",
    remove: "移除",
    removeTitle: "移除通知渠道？",
    removeConfirm: (name: string) => `之后不会再向「${name}」发送告警，需要时可以重新连接。`,
    cancel: "取消",
    testSent: "测试告警已发送",
    testFailed: (error: string) => `测试失败：${error}`,
    removed: "已移除通知渠道",
    paused: "已暂停",
    digestAt: (time: string) => `每日汇总 ${time}`,
    remindEvery: (h: number) => `${h < 24 ? `${h} 小时` : "1 天"}未处理提醒`,
    connected: "渠道已连接。发送一条测试看看告警的样子。",
    oauthError: {
      cancelled: "已取消连接。",
      state: "连接已过期或不是在这里发起的，请重试。",
      exchange: "对方服务没有返回频道，请重试。",
      unknown: "未知的集成。",
    } as Record<string, string>,
    readOnly: "只有管理员和项目经理可以修改告警发送的位置。",
    noKey: "告警未开启：需要在服务器上设置 ASSAY_SECRET_KEY 才能保存渠道密钥。",
    loadFailed: "无法加载通知设置",
    count: (n: number) => `${n} 个通知渠道`,
  },
};
